FROM python:3.12-alpine

ARG TARGETARCH=amd64
ARG KUBECTL_VERSION=v1.33.3

RUN apk add --no-cache ca-certificates curl \
    && curl -fsSLo /usr/local/bin/kubectl \
      "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/${TARGETARCH}/kubectl" \
    && chmod 0755 /usr/local/bin/kubectl

WORKDIR /build
COPY pyproject.toml /build/
COPY src /build/src
RUN pip install --no-cache-dir /build \
    && addgroup -g 10001 -S agentx \
    && adduser -u 10001 -S -D -G agentx agentx \
    && rm -rf /build

USER 10001:10001
WORKDIR /home/agentx
ENTRYPOINT ["agentx-service"]
CMD ["serve"]
